spring:
   config:
     activate:
       on-profile: "prod"

build:
   version: "1.0"

accounts:
  message: "Cards MicroService"
  contactDetails:
    name: "Rohan"
    email: "rohan@companyname.com"
  env: "Prod"