services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "sshah79/config:l1"
    container_name: configserver-service
    ports:
      - "8090:8090"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  servicediscoveryserver:
    image: "sshah79/service-discovery:l1"
    container_name: servicediscovery-service
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  accounts:
    image: "sshah79/accounts:l1"
    container_name: accounts-service
    ports:
      - "8080:8080"
    depends_on:
      servicediscoveryserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-servicediscovery-config

  loans:
    image: "sshah79/loans:l1"
    container_name: loans-service
    ports:
      - "8082:8082"
    depends_on:
      servicediscoveryserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-servicediscovery-config

  cards:
    image: "sshah79/cards:l1"
    container_name: cards_service
    ports:
      - "8081:8081"
    depends_on:
      servicediscoveryserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-servicediscovery-config

  #gatewayserver:
    #image: "trainingoct/gatewayserver:l3"
    #container_name: gatewayserver-ms
    #ports:
     # - "8072:8072"
    #depends_on:
     # accounts:
      #  condition: service_healthy
    #  loans:
     #   condition: service_healthy
      #cards:
       # condition: service_healthy
    #environment:
     # SPRING_APPLICATION_NAME: "gatewayserver"
    #extends:
     # file: common-config.yml
      #service: microservice-servicediscovery-config

networks:
  globalbank:
    driver: "bridge"